### PR TITLE
fix(alert, toast, doc): default values in api doc for alert and toast

### LINKED ISSUE #681: API default values for Alert and Toast are not shown in the Demo website
**Description**
After navigation to https://amadeusitgroup.github.io/AgnosUI/main/docs/svelte/components/alert/api observe that the default values of the alert and toast props are not shown.

### PR DESCRIPTION
**Pull request by quentinderoubaix**
closes #681

### CODE REVIEW

File: scripts/doc/api-doc.ts [hunk 1]
```diff
@@ -263,16 +285,17 @@ export function parseDocs(indexFile: string) {
...
 
 	function visitType(node: Node) {
+		const flags = ts.TypeFormatFlags.InTypeAlias | ts.TypeFormatFlags.NoTruncation;
 		if (ts.isFunctionLike(node) && node.name) {
 			const symbol = typeChecker.getSymbolAtLocation(node.name)!;
 			const res = typeChecker.typeToString(typeChecker.getTypeOfSymbolAtLocation(symbol, node));
 			return res;
 		}
-		if ((node as HasType)?.type) {
+		if ((node as HasType)?.type && (node as HasType).type!.getText().startsWith('SlotContent<')) {
```
Comment (andreascorti) [inline scripts/doc/api-doc.ts:294]: Question: what does it solve this `startWith`?

**Review by andreascorti — APPROVED** [review]
LGTM, thanks @quentinderoubaix ! I'm ok with the layout, but be sure it is ok for all contributors.

File: scripts/doc/api-doc.ts (hunk 1 above)
Comment (quentinderoubaix) [reply scripts/doc/api-doc.ts:294]: As discussed, it was to display the type of the item transition.
